---
- name : Creating launch configuraion for ASG
  ec2_lc:
    name: Infinity-app-lc
    aws_access_key: '{{ VAULT_AWS_ACCESS_KEY }}'
    aws_secret_key: '{{ VAULT_AWS_SECRET_KEY }}'
    region: us-east-1
    image_id: ami-0a887e401f7654935
    key_name: vagrant_test    
    security_groups: sg-5b48530d
    instance_type: t2.micro
#    instance_tags:
#      Name: Infinity-app-ec2
#      Env: dev
    volumes:
      - device_name: /dev/xvda
        volume_size: 8
        delete_on_termination: true
  register: launchconfig 

- name: Debug mode for launchconfig.target_group_arn
  debug:
      var: launchconfig

