---
- name : Creating an Application Load Balancer
  elb_application_lb:
    aws_access_key: '{{ VAULT_AWS_ACCESS_KEY }}'
    aws_secret_key: '{{ VAULT_AWS_SECRET_KEY }}'
    name: Infinity-app-lb
    security_groups:
            - sg-5b48530d
    subnets:
            - subnet-9b1d03b5
            - subnet-b363a9bd
    listeners:
            - Protocol: HTTPS
              Port: 443
              SslPolicy: ELBSecurityPolicy-FS-1-2-2019-08
              Certificates:
                      - CertificateArn: arn:aws:iam::260450533524:server-certificate/jo-x509
              DefaultActions: 
                      - Type: forward
                        TargetGroupName: Infinity-app-tg
    state: present   

