---
- name: Creating a Traget group 
  elb_target_group:
    name : Infinity-app-tg
    aws_access_key: '{{ VAULT_AWS_ACCESS_KEY }}'
    aws_secret_key: '{{ VAULT_AWS_SECRET_KEY }}'
    protocol: http
    port: 80
    vpc_id: vpc-a0fed2da
    state: present
  register: tg
- debug: var=tg.target_group_arn

